[package]
name = "quantities"
version = "0.1.0"
edition = "2024"

[dependencies]
quantities-macros = { workspace = true}
derive_more = { version = "2.1.1", features = ["full"]}

[features]
electricity = []
default = ["electricity"]