[workspace]
members = [
  "quantities",
  "quantities-macros",
]
resolver = "2"
default-members = ["quantities"]

[workspace.dependencies]
quantities = { path = "./quantities" }
quantities-macros = { path = "./quantities-macros" }