edition = "2024"
max_width = 70
fn_call_width = 50
hard_tabs=true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

# Nightly options
unstable_features = true
wrap_comments = true
comment_width = 75
fn_single_line = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 70
format_strings = true
float_literal_trailing_zero = "IfNoPostfix"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"

